### ISSUE TITLE
Reward attribution when breaking blocks without permission

### ISSUE THREAD

**Issue by wtfrankjs** [joserodpt/RealMines#65]
I am experiencing an issue with the RealMines plugin on my Minecraft server. When players mine blocks from a specific mine, they receive multiple rewards instead of just one. The issue persists regardless of the reward configuration.

Here are the steps I have already taken to try and resolve the issue:

Verified the mines.yml configuration file to ensure rewards are not duplicated or overlapping.
Checked the chance values for each reward to ensure they do not all trigger at once.
Updated RealMines to the latest version available.
Tested the plugin on a separate server with no other plugins to avoid conflicts.
Enabled or checked the exclusive_rewards setting (if available) to ensure only one reward is given per action.

Minecraft server version: (1.21.1)
RealMines plugin version: (1.8.2 in config:8)

**Comment by wtfrankjs** [comment]
After the lowest level values, it gives the values ​​before it, it gives all of them

config:

`name: Mine4
type: BLOCKS
world: madenalani
icon: DEEPSLATE_REDSTONE_ORE
displayName: Mine4
color: BLUE
pos1: 15;64;1
pos2: 1;52;-13
reset:
  silent: false
  commands: []
  percentage:
    active: false
    value: 20
  time:
    active: false
    value: 120
settings:
  break-permission: true
  discard-break-action-messages: false
  block-sets-mode: INCREMENTAL
signs: []
block-sets:
  default:
    description: 'Description for block set: default'
    icon: CAULDRON
    blocks:
      STONE:
        percentage: 0.5
        disabled-vanilla-drop: true
        disabled-block-mining: false
      REDSTONE_ORE:
        percentage: 0.5
        disabled-vanilla-drop: false
        disabled-block-mining: false
        break-actions:
          action-vcsmdmxe-1736194795:
            type: EXECUTE_COMMAND
            chance: 5.0
            value: eco give %player% 500
          action-ncyohngz-1736194930:
            type: EXECUTE_COMMAND
            chance: 10.0
            value: eco give %player% 200
          action-tqpihxwp-1736194956:
            type: EXECUTE_COMMAND
            chance: 15.0
            value: eco give %player% 100
          action-ohvdrkjq-1736194976:
            type: EXECUTE_COMMAND
            chance: 15.0
            value: eco give %player% 50
          action-yhpobukt-1736194994:
            type: EXECUTE_COMMAND
            chance: 25.0
            value: eco give %player% 20
teleport: 6;56;-3;46.77881;32.078255
`

**Comment by wtfrankjs** [comment]
every mine is same and the issiue is same purpur 1.21.1

**Comment by wtfrankjs** [comment]
I discovered another bug. When I close the event and deactivate block breaking, when they break the block, it does not break, but the reward continues to come.

**Comment by wtfrankjs** [comment]
Do you will fix ?

**Comment by joserodpt** [comment]
This will be fixed when I have time

**Comment by joserodpt** [comment]
Regarding your first issue, it has been solved in the .jar file attached below, please test it and give me some feedback: 
[RealMines.jar.zip](https://github.com/user-attachments/files/18446680/RealMines.jar.zip)

Regarding your other issue "deactivate block breaking, when they break the block, it does not break, but the reward continues to come." couldn't reproduce this behaviour, so it is working as intended. If it still happens with that build, send more details as to how can I reproduce it.

**Comment by wtfrankjs** [comment]
I have 4 mining areas within a protected region using WorldGuard, and each area should be accessible to players with different ranks. However, there's an ongoing issue where players without the proper rank can still receive rewards when breaking blocks in areas they don’t have permission for. For example, when a regular player breaks blocks in the VIP area from the outside, they still get rewards, even though the blocks don’t actually break due to protections.

**Comment by joserodpt** [comment]
That's alão a good report. Are you using RealMines as protection? If not, what plugin are you using?

**Comment by neziw** [comment]
going to close this issue due to inactivity
